apiVersion: apps/v1
kind: Deployment
metadata:
  name: dof-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: dof
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dof
    spec:
      containers:
      - name: app-cont
        image: bgatanasov/dof-learning:20210922.184941
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: dof-svc
  labels:
    app: dof
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31002
    protocol: TCP
  selector:
    app: dof
